kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admission-sa-role-ingress
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - config.openshift.io
    resources:
      - dnses
  - verbs:
      - get 
      - list
    apiGroups:
      - ""
    resources:
      - services
