name: Build
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      packages: write

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Build
        run: |
          make build

      - name: Log in to registry.redhat.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PULLSECRET }}
          registry: registry.redhat.io

      - name: Build image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          context: .
          dockerfiles: Dockerfile
          image: admission-controller
          oci: true
          tags: ${{ github.sha }}

      - name: Push to ghcr.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          registry: ghcr.io/${{ github.repository }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: ${{ steps.build_image.outputs.tags }}